### ISSUE TITLE
Ensure Ecto projections works with Commanded's event handler `error/3` callback

### ISSUE THREAD

**Issue by slashdotdash** [commanded/commanded-ecto-projections#10]
Defining an `error/3` callback in a projection, using Commanded's event handler ([#133](https://github.com/commanded/commanded/pull/133)), and returning `:skip` should ignore the problematic event and allow the projection to continue.

**Comment by sardaukar** [comment]
Is there no current way to do error handling?

**Comment by slashdotdash** [comment]
@sardaukar It needs to be tested using the `error/3` callback.

**Comment by sardaukar** [comment]
I tried returning an error tuple from `project/2` on a projection with `error/3` defined and got this on a test for it:

<pre>
The following arguments were given to Ecto.Repo.Queryable.transaction/4:

         # 1
         Ecto.Adapters.Postgres

         # 2
         Toby.Repo

         # 3
         {:error, :reason}

         # 4
         [timeout: :infinity, pool_timeout: :infinity]

     Attempted function clauses (showing 2 out of 2):

         def transaction(adapter, repo, fun, opts) when is_function(fun, 0)
         def transaction(adapter, repo, %Ecto.Multi{} = multi, opts)

     code: Projector.handle(task_assigned_evt, %{
     stacktrace:
       (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.transaction/4
       (toby) lib/projections/ecto.ex:74: Toby.Projectors.Task.AssignedTasks.update_projection/3
       test/toby/projectors/task/assigned_tasks_test.exs:17: (test)
</pre>

The test:

```
test "should not project" do
      task_assigned_evt = build(:task_assigned_event)

      last_seen_event_number =
        get_last_seen_event_number("Projectors.Task.AssignedTasks")

      assert :skip =
               Projector.handle(task_assigned_evt, %{
                 event_number: last_seen_event_number + 1
               })
    end
```

What am I doing wrong?

**Comment by slashdotdash** [comment]
If you're testing the `handle/2` function directly then it should return the error you've defined. This error, the failed event, and a `FailureContext` struct are then passed to the `error/3` function:

```elixir
alias Commanded.Event.FailureContext

assert {:error, error} = Projector.handle(task_assigned_evt, %{
  event_number: last_seen_event_number + 1
})

assert :skip = Projector.error({:error, error}, task_assigned_evt, %FailureContext{})
```

**Comment by sardaukar** [comment]
I see. Thanks!
