### ISSUE TITLE
Ecto projector shutting down service when invalid event

### ISSUE THREAD

**Issue by sebastialonso** [commanded/commanded-ecto-projections#16]
I've propagated an event with an string value in an integer field.

While easy to correct, there seems to be a catastrophic failure within Commanded

~~~
[warn] Exercises.Evaluations.Projectors.Assignment has requested to stop: %Ecto.ChangeError{message: "value `\"20\"` for `Exercises.Evaluations.Projections.Assignment.group_id` in `insert` does not match type :integer"}
[error] GenServer {Commanded.Registration.LocalRegistry, {Commanded.Event.Handler, "Evaluations.Projectors.Assignment"}} terminating
** (stop) %Ecto.ChangeError{message: "value `\"20\"` for `Exercises.Evaluations.Projections.Assignment.group_id` in `insert` does not match type :integer"}
Last message: {:events, [%Commanded.EventStore.RecordedEvent{causation_id: "06c166e2-026e-4da9-a66e-a70c1fc5f0cc", correlation_id: "b15ed36a-cf50-4154-8efd-87049b37bf4b", created_at: ~N[2018-11-19 21:54:40.135747], data: %Exercises.Evaluations.Events.AssignmentSaved{group_id: "20", module_id: "lGH3LWcBJBlBGoN6S-qk", rubric_id: "430d19e3-fe63-44d9-bd66-cd5b9100e552", state: "waiting_for_evaluation", user_id: 5, uuid: "14ea36bb-8252-4268-b9a9-99cbd2049a48"}, event_id: "38ba6ed9-f9cb-4207-af4b-aae7d25a8278", event_number: 21, event_type: "Elixir.Exercises.Evaluations.Events.AssignmentSaved", metadata: %{}, stream_id: "14ea36bb-8252-4268-b9a9-99cbd2049a48", stream_version: 1}]}
State: %Commanded.Event.Handler{consistency: :strong, handler_module: Exercises.Evaluations.Projectors.Assignment, handler_name: "Evaluations.Projectors.Assignment", last_seen_event: nil, subscribe_from: :origin, subscription: #PID<0.462.0>}
[info] Application exercises exited: shutdown
~~~

I haven't found how to restart the service. How can I do that? Do I need to delete the ill-formed event?

Thanks!

**Comment by slashdotdash** [comment]
If this is in a test or development environment then you can clear your event store to resolve the problem. In production you would need to either convert the string to an integer in the projector or using an [event decoder during deserialization](https://github.com/commanded/commanded/blob/master/guides/Serialization.md).

**Comment by sebastialonso** [comment]
It's on development.

Thanks for the deserialization bit!

**Comment by shadiramadan** [comment]
@slashdotdash Is there a recommended way to not have a failing projector crash the entire app in production?
I'd rather that the projector keeps failing than to kill the whole app and any other functionality.

That also makes it easier to open up a remote shell and investigate / troubleshoot the bad event.

**Comment by slashdotdash** [comment]
> @slashdotdash Is there a recommended way to not have a failing projector crash the entire app in production?
> I'd rather that the projector keeps failing than to kill the whole app and any other functionality.

An Ecto projector is a Commanded event handler so you can implement your own [`error/3` callback function](https://hexdocs.pm/commanded/Commanded.Event.Handler.html#c:error/3) to handle errors, such as skip problematic events or retry with optional delay. There's an [example Commanded's event handler documentation](https://hexdocs.pm/commanded/Commanded.Event.Handler.html#c:error/3-example-error-handling).

```elixir
def error(error, event, %FailureContext{context: context}) do
  failures = Map.get(context, :failures, 1)

  # Retry event after an exponential delay, failure count is included in context map
  delay = :timer.seconds(1) * failures
  context = Map.put(context, :failures, failures + 1)

  {:retry, delay, context}
end

```
