### ISSUE TITLE
[Regression] Timestamp fields in `projection_versions` are missing microseconds.

### ISSUE THREAD

**Issue by datafoo** [commanded/commanded-ecto-projections#21]
[Ecto](https://github.com/elixir-ecto/ecto) 3.0 introduced some [breaking changes](https://github.com/elixir-ecto/ecto/blob/master/CHANGELOG.md#backwards-incompatible-changes-1):

> [Ecto.Schema] :time, :naive_datetime and :utc_datetime no longer keep microseconds information. If you want to keep microseconds, use :time_usec, :naive_datetime_usec, :utc_datetime_usec

Since the `timestamps` macro uses `:naive_datetime` by default (https://hexdocs.pm/ecto/Ecto.Schema.html#timestamps/1), there has been a breaking change in [commanded-ecto-projections](https://github.com/commanded/commanded-ecto-projections) when migrating to Ecto 3.0.

```elixir
schema "projection_versions" do
    field(:last_seen_event_number, :integer)

    timestamps()
end
```
Source: https://github.com/commanded/commanded-ecto-projections/blob/master/lib/projections/ecto.ex

**Comment by slashdotdash** [comment]
Good catch. It looks as though setting the timestamp type as `:naive_datetime_usec` would fix this.

```elixir
timestamps(type: :naive_datetime_usec)
```
