### ISSUE TITLE
question: Does after_update run after all the projection are executed?

### ISSUE THREAD

**Issue by Rockson** [commanded/commanded-ecto-projections#29]
I think it's not clear if the after_update runs after the single projection or after the whole transaction.
Also, would resetting the projection trigger the after_update? If so, it doesn't look a good point where to place the publishing to a channel.
Anyway thanks for this awesome project!

**Comment by slashdotdash** [comment]
The `after_update/3` callback runs after each projected event.

Yes, when rebuilding a projection you would want to temporarily disable any publishing. Once the projection has caught up you could enable it again. Each event as an event number which could be used to determine whether to publish it or not (e.g. if event_number < x don't publish).

**Comment by Rockson** [comment]
Ok that makes sense, anyway I think that I would need to publish an event after all the projections that a command triggers are executed. I'm using graphql, and the subscription data is controlled client-side.
I think that in this case dispatching the command with strong consistency and sending the event to the channel right after would do it.
Does it make sense to you?
