### ISSUE TITLE
Events not projected in order?

### ISSUE THREAD

**Issue by larskluge** [commanded/commanded-ecto-projections#30]
Hi there, I am fairly new to commanded, so perhaps this is a stupid question.. 

I pushed some events (~800,000 events w/ relatively large payload) through commanded into Postgres eventstore and now trying to use `commanded-ecto-projections` to project these. The order of events is important however. 

Checking in Postgres for one example shows the correct and expected order: 

<img width="622" alt="image" src="https://user-images.githubusercontent.com/115296/73588946-071fd800-4502-11ea-8606-53e006193f31.png">

Now when I use `commanded-ecto-projections` unfortunately I get the second event before the first one. My projector is super simple and no pattern matching prevents the first event from being filtered. 

Is the same order of events not guaranteed as registered in event store's events table?

Thank you!

**Comment by slashdotdash** [comment]
The order of events in a stream is determined by the `stream_version` column in the `stream_events` table. You can run the following SQL query for a given stream id to get ordered events. Stream id 0 is the global “all events” stream. 

A Commanded event handler is guaranteed to receive events in the order they appear in the stream. An Ecto projector is just a specialised Commanded event handler. 

If you can create a code sample to reproduce the issue you are seeing I will take a look.

**Comment by larskluge** [comment]
Thank you for this @slashdotdash ! It's good to know the guarantee. 

Not sure which stream the projector runs on, but either way, joined w/ `stream_events` and ordered by `stream_version`, it still is the correct order: 

<img width="896" alt="image" src="https://user-images.githubusercontent.com/115296/73598324-cb662c00-455c-11ea-81be-b71c12892861.png">

Will dig a bit more and if that does not help will try to create some code to reproduce.

**Comment by larskluge** [comment]
Ok, this must have been my fault. I can't reproduce and its gone. Rebuilt the projection from scratch, first time exploded again, second time runs smoothly now, probably all the way through to the end. 

Reason was probably some unclean state while developing the projector *or* some unclean state was produced when shutting down the development Elixir process while projecting (`CTRL+\`) and upon continue it exploded then.. 

However, this is not a bug in this project. Closing this issue. Thanks for your help!
